name: test with coverage
on:
  push:
    branches:
      - main
    tags:
      - '**'
    paths:
      - src/*
      - __tests__/*
      - '*.json'
      - yarn.lock

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm build
      - run: npm test
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm build
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        node-version: '12'
        token: ${{secrets.GT}}
        coverageCommand: npm run coverage
        debug: true