name: test with coverage
on:
  push:
    branches:
      - main
    tags:
      - '**'
    paths:
      - src/*
      - __tests__/*
      - '*.json'
      - yarn.lock

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm build
      - run: npm test
  coverage:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm build
      - run: npm run coverage